extends:
  - '@commitlint/config-conventional'

rules:
  header-max-length: [1, always, 70]
  header-full-stop: [2, never, '.']
  type-case: [2, always, lower-case]
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - ci
      - chore
      - revert
  signed-off-by: [2, always, 'Signed-off-by:']
  trailer-exists: [2, always, 'Signed-off-by:']
  subject-empty: [2, never]
  subject-case: [2, always, sentence-case]
  subject-full-stop: [2, never, '.']
  body-min-length: [2, always, 1]
  body-max-line-length: [2, always, 250]
  scope-empty: [0, always]
  scope-case: [2, always, lower-case]
  scope-enum:
    - 2
    - always
    - - release

parserPreset:
  parserOpts:
    headerCorrespondence: ['type', 'scope', 'subject']
    issuePrefixes: ['#']
    referenceActions: ['Closes', 'Fixes', 'Resolves']
    noteKeywords: ['BREAKING CHANGE']
